services:
  pupesoft:
    image: localhost/pupesoft7
    depends_on:
      - "mariadb"
    env_file: "pupesoft.env"
    ports:
      - "8080:80"
    networks:
      - pupesoft-network
    restart: on-failure

  mariadb:
    image: "mariadb:11.7"
    volumes:
      - "./pupesoft7/alkudata_pupesoft7.sql:/docker-entrypoint-initdb.d/alkudata_pupesoft7.sql"
      - "./data:/var/lib/mysql"
    env_file: "pupesoft.env"
    networks:
      - pupesoft-network
    restart: on-failure

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    depends_on:
      - "mariadb"
    environment:
      PMA_HOST: "mariadb"
      PMA_PORT: "3306"
      UPLOAD_LIMIT: "256M"
    ports:
      - "8081:80"
    networks:
      - pupesoft-network

networks:
  pupesoft-network:
